### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by barepixels** [Arminius-Software/face2video#1]
No module named 'cv2' but I have opencv-python installed

![cv2b](https://github.com/Arminius-Software/face2video/assets/92839033/24141b41-211c-4f8b-b7ed-dd0d55e37506)

**Comment by Arminius-Software** [comment]
Hi, try the following.

"python -m pip install --upgrade pip"
"pip uninstall opencv-python"
"python -m pip install opencv-python"

If that does not work let me know.

**Comment by barepixels** [comment]
sadly it did not work
1) upgraded  pip
2) Successfully uninstalled opencv-python-4.8.0.76
3) Successfully installed opencv-python-4.8.1.78

![cv2c](https://github.com/Arminius-Software/face2video/assets/92839033/218bcf88-bbb6-43af-adae-019b0eaad741)

**Comment by Arminius-Software** [comment]
I just tested it again in a clean virtual environment, and these are all the libraries that the installer should download for you:

certifi==2023.11.17
charset-normalizer==3.3.2
colorama==0.4.6
decorator==4.4.2
idna==3.4
imageio==2.33.0
imageio-ffmpeg==0.4.9
moviepy==1.0.3
numpy==1.26.2
opencv-contrib-python==4.8.1.78
opencv-python==4.8.0.76
Pillow==10.1.0
proglog==0.1.10
requests==2.31.0
tqdm==4.66.1
urllib3==2.1.0

I assume you have something old installed that is causing conflicts. But you can simply run the program in a virtual environment. First, place the video and face files into the folders and enter the paths into main.py. Then, go into cmd with the path to the project. Finally, run the following commands:

"python -m venv venv"
"venv\Scripts\activate"
"python install.py"
"python main.py"

**Comment by barepixels** [comment]
```
"python -m venv venv"
"venv\Scripts\activate"
"python install.py"
"python main.py"
```

it's working now.  thank you.  extracted_frames folder starts to fill up

**Comment by Arminius-Software** [comment]
Awesome!
