### ISSUE TITLE
Cannot get GUI to show

### ISSUE THREAD

**Issue by Usr45** [Arminius-Software/face2video#4]
I can easily run the utility by typing `python main.py` (and it will process the hardcoded file names I place in the python file), but based on the verbiage in step 2:

> Run the main.py file to start the gui.

I never receive any type of GUI. Am I missing something?

Running this on a Windows 11 machine. 

That aside, this is a fantastic utility. Great job!

**Comment by Arminius-Software** [comment]
Are you using the newest version? The GUI was added later on. If you downloaded this a while ago, I suggest deleting your current folder and then cloning the git again. Also, make sure to run the install.py file once before running the main.py file.

**Comment by Usr45** [comment]
Ha, yep, there you go. I thought I had the latest, apparently not. 

Sorry and thanks!
